import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

export const createTodayStyles = (Colors: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 24,
      paddingTop: 100,
    },
    // Top Bar
    topBar: {
      position: 'absolute',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingBottom: 12,
      backgroundColor: 'rgba(248, 250, 252, 0.7)',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 10,
    },
    topBarLeft: {
      width: 40,
    },
    menuButton: {
      padding: 4,
      borderRadius: 999,
      backgroundColor: 'rgba(0,0,0,0.05)',
    },
    topBarCenter: {
      alignItems: 'center',
    },
    topBarTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: Colors.primary,
    },
    topBarDate: {
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: Colors.onSurfaceVariant,
      marginTop: 2,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: Colors.surfaceContainerHighest,
      borderWidth: 2,
      borderColor: `${Colors.primary}10`,
    },
    // Daily Progress
    progressSection: {
      marginTop: 0,
      marginBottom: 24,
    },
    progressLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: `${Colors.primary}70`,
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    progressHeader: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'center',
      gap: 8,
      marginBottom: 16,
    },
    progressCurrent: {
      fontSize: 48,
      fontWeight: '800',
      color: Colors.primary,
    },
    progressGoal: {
      fontSize: 16,
      fontWeight: '500',
      color: Colors.onSurfaceVariant,
    },
    progressBarContainer: {
      height: 8,
      backgroundColor: Colors.surfaceContainerHigh,
      borderRadius: 999,
      overflow: 'hidden',
      marginTop: 8,
    },
    progressSubText: {
      fontSize: 13,
      color: Colors.onSurfaceVariant,
      marginTop: 4,
      marginBottom: 6,
    },
    progressBarFill: {
      height: '100%',
      backgroundColor: Colors.primary,
      borderRadius: 999,
    },
    // Active Session Card
    activeSessionCard: {
      borderRadius: 32,
      marginBottom: 24,
      overflow: 'hidden',
      position: 'relative',
      backgroundColor: 'rgba(255,255,255,0.7)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 4,
    },
    glassOverlay: {
      position: 'absolute',
      top: -48,
      right: -48,
      width: 128,
      height: 128,
      borderRadius: 64,
      backgroundColor: `${Colors.tertiary}20`,
    },
    cardContent: {
      padding: 32,
      alignItems: 'center',
    },
    activeBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: `${Colors.tertiaryContainer}10`,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      marginBottom: 16,
    },
    pulseDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: Colors.tertiary,
      position: 'absolute',
    },
    staticDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: Colors.tertiary,
    },
    activeBadgeText: {
      fontSize: 10,
      fontWeight: 'bold',
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: Colors.tertiary,
    },
    sessionTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: Colors.primary,
      marginBottom: 4,
      textAlign: 'center',
    },
    sessionProject: {
      fontSize: 12,
      color: Colors.onSurfaceVariant,
      marginBottom: 24,
      textAlign: 'center',
    },
    timerDisplay: {
      fontSize: 56,
      fontWeight: '800',
      color: Colors.onSurface,
      marginBottom: 32,
      fontVariant: ['tabular-nums'],
    },
    stopButton: {
      width: '100%',
      borderRadius: 999,
      overflow: 'hidden',
    },
    stopButtonGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 16,
    },
    stopButtonText: {
      fontSize: 16,
      fontWeight: '800',
      color: Colors.onPrimary,
    },
    // Timeline Header
    timelineHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    timelineHeaderTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: Colors.primary,
    },
    timelineSubHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
      marginTop: 6,
    },
    daySummaryRow: {
      backgroundColor: Colors.surfaceContainerLow,
      borderRadius: 18,
      paddingVertical: 12,
      paddingHorizontal: 14,
      marginBottom: 10,
    },
    daySummaryLeft: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    daySummaryDay: {
      fontSize: 14,
      fontWeight: '800',
      color: Colors.primary,
    },
    daySummaryWorked: {
      fontSize: 12,
      color: Colors.onSurfaceVariant,
    },
    daySummaryBarContainer: {
      height: 6,
      width: '100%',
      backgroundColor: Colors.surfaceContainerHigh,
      borderRadius: 999,
      overflow: 'hidden',
    },
    daySummaryBarFill: {
      height: '100%',
      backgroundColor: Colors.secondary,
    },
    seeAllButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    seeAllText: {
      fontSize: 12,
      fontWeight: '600',
      color: Colors.primary,
    },
    // Timeline Items
    timelineItem: {
      backgroundColor: Colors.surfaceContainerLow,
      borderRadius: 24,
      padding: 20,
      marginBottom: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    timelineLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      flex: 1,
    },
    timelineIconBg: {
      width: 48,
      height: 48,
      borderRadius: 24,
      justifyContent: 'center',
      alignItems: 'center',
    },
    timelineTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: Colors.onSurface,
      marginBottom: 4,
    },
    timelineTime: {
      fontSize: 11,
      color: Colors.onSurfaceVariant,
    },
    timelineRight: {
      alignItems: 'flex-end',
    },
    timelineDuration: {
      fontSize: 16,
      fontWeight: '800',
      color: Colors.primary,
      marginBottom: 4,
    },
    categoryBadge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
    },
    categoryText: {
      fontSize: 10,
      fontWeight: 'bold',
      textTransform: 'uppercase',
    },
    // Bottom Navigation
    bottomNav: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.8)',
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      paddingVertical: 8,
      paddingHorizontal: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 8,
    },
    navItem: {
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 16,
    },
    navItemActive: {
      backgroundColor: `${Colors.primary}10`,
    },
    navLabel: {
      fontSize: 10,
      marginTop: 4,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      color: Colors.outline,
    },
    navLabelActive: {
      color: Colors.primary,
      fontWeight: 'bold',
    },
    // FAB
    fab: {
      position: 'absolute',
      right: 24,
      bottom: 112,
      width: 64,
      height: 64,
      borderRadius: 32,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
      zIndex: 20,
    },
    fabGradient: {
      flex: 1,
      borderRadius: 32,
      justifyContent: 'center',
      alignItems: 'center',
    },
    // Placeholders
    placeholderScreen: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
    },
    placeholderTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: Colors.primary,
      marginBottom: 8,
    },
    placeholderSub: {
      fontSize: 16,
      color: Colors.onSurfaceVariant,
      textAlign: 'center',
    },
    noDaysCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: Colors.surfaceContainerHigh,
      backgroundColor: Colors.surfaceContainerLowest,
      paddingVertical: 20,
      paddingHorizontal: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
    },
    noDaysText: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
      fontWeight: '600',
    },
  });

export const createCurrentWeekStyles = (Colors: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 24,
      paddingTop: 100,
    },
    // Top Bar
    topBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingBottom: 16,
      backgroundColor: Colors.background,
    },
    topBarLeft: {
      width: 40,
    },
    menuButton: {
      padding: 4,
      borderRadius: 999,
      backgroundColor: 'rgba(0,0,0,0.05)',
    },
    topBarCenter: {
      alignItems: 'center',
    },
    topBarTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: Colors.primary,
    },
    topBarDate: {
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: Colors.onSurfaceVariant,
      marginTop: 2,
    },
    profileSection: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
    },
    logoText: {
      fontSize: 24,
      color: Colors.primary,
    },
    // Hero
    hero: {
      marginBottom: 24,
    },
    heroTitle: {
      fontSize: 32,
      color: Colors.onBackground,
      marginBottom: 8,
    },
    heroSubtitle: {
      fontSize: 16,
      color: Colors.onSurfaceVariant,
      lineHeight: 24,
    },
    highlight: {
      color: Colors.primary,
    },
    // Action Row
    actionRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 24,
    },
    gradientButton: {
      flex: 1,
      borderRadius: 12,
      backgroundColor: Colors.primary,
      paddingVertical: 14,
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
    },
    outlineButton: {
      flex: 1,
      borderRadius: 12,
      paddingVertical: 14,
      minHeight: 48,
      borderWidth: 1,
      borderColor: Colors.outlineVariant,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    buttonInner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderRadius: 10,
    },
    buttonText: {
      fontSize: 16,
      color: Colors.onPrimary,
    },
    outlineButtonText: {
      fontSize: 16,
      color: Colors.primary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 16,
    },
    modalCardScroll: {
      flexGrow: 1,
      width: '100%',
    },
    modalCard: {
      width: '92%',
      maxHeight: '88%',
      backgroundColor: Colors.surface,
      borderRadius: 20,
      paddingVertical: 14,
      paddingHorizontal: 14,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 12,
    },
    modalTitle: {
      fontSize: 20,
      marginBottom: 12,
      color: Colors.onBackground,
    },
    modalLabel: {
      fontSize: 12,
      color: Colors.onSurfaceVariant,
      marginTop: 8,
      marginBottom: 4,
    },
    modalInput: {
      borderWidth: 1,
      borderColor: Colors.surfaceContainerHigh,
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 8,
    },
    rowInput: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
      gap: 8,
    },
    smallButton: {
      minWidth: 36,
      minHeight: 36,
      borderRadius: 8,
      backgroundColor: Colors.surfaceContainer,
      alignItems: 'center',
      justifyContent: 'center',
    },
    smallButtonText: {
      fontSize: 20,
      color: Colors.primary,
    },
    modalValue: {
      fontSize: 16,
      color: Colors.onBackground,
      width: 40,
      textAlign: 'center',
    },
    dayEntryRow: {
      marginBottom: 6,
    },
    dayEntryLabel: {
      fontSize: 12,
      color: Colors.onSurfaceVariant,
      marginBottom: 3,
    },
    datePickerInline: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    modalActions: {
      flexDirection: 'row',
      marginTop: 8,
    },
    emptyState: {
      marginTop: 16,
      borderRadius: 16,
      backgroundColor: Colors.surfaceContainerLow,
      padding: 20,
      alignItems: 'center',
    },
    emptyText: {
      color: Colors.outlineVariant,
      textAlign: 'center',
    },
    monthlySummary: {
      marginTop: 12,
      borderRadius: 16,
      backgroundColor: Colors.surfaceContainerLow,
      padding: 16,
      alignItems: 'center',
    },
    monthlySummaryTitle: {
      fontSize: 12,
      color: Colors.onSurfaceVariant,
      marginBottom: 4,
    },
    monthlySummaryValue: {
      fontSize: 24,
      color: Colors.primary,
      fontWeight: '800',
      marginBottom: 2,
    },
    monthlySummarySub: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
    },
    weekCard: {
      backgroundColor: Colors.surface,
      borderRadius: 16,
      overflow: 'hidden',
      marginBottom: 16,
      shadowColor: Colors.inverseSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    weekCardTouchable: {
      width: '100%',
      padding: 20,
    },
    weekCardFooter: {
      flexDirection: 'row',
      borderTopWidth: 1,
      borderTopColor: Colors.surfaceContainerHigh,
      marginBottom: 4,
    },
    weekCardFooterButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 12,
    },
    weekCardFooterText: {
      fontSize: 13,
      color: Colors.primary,
    },
    editWeekButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
      backgroundColor: Colors.surfaceContainerLow,
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 12,
    },
    editWeekText: {
      fontSize: 14,
      color: Colors.primary,
      marginLeft: 6,
    },
    activeBadge: {
      position: 'absolute',
      top: 12,
      right: 12,
      backgroundColor: Colors.primaryFixed,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
    },
    activeBadgeText: {
      fontSize: 12,
      color: Colors.primary,
    },
    dateRangeText: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
      marginBottom: 4,
    },
    totalHoursText: {
      fontSize: 28,
      color: Colors.onSurface,
      marginBottom: 4,
    },
    progressSection: {
      marginBottom: 16,
    },
    progressHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    progressLabel: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
    },
    goalText: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
    },
    customLabel: {
      fontSize: 14,
    },
    progressBarContainer: {
      height: 8,
      backgroundColor: Colors.surfaceContainerHigh,
      borderRadius: 4,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: 4,
    },
    dayIndicators: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    dayRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 10,
    },
    dayCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayLetter: {
      fontSize: 14,
    },
    timerCard: {
      backgroundColor: Colors.surface,
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: Colors.inverseSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    timerLeft: {
      flex: 1,
    },
    pulseContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    pulseDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: Colors.error,
      position: 'absolute',
    },
    staticDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: Colors.error,
    },
    trackingLabel: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
    },
    timerDisplay: {
      fontSize: 32,
      color: Colors.onSurface,
      marginBottom: 4,
    },
    projectName: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
    },
    stopButton: {
      backgroundColor: Colors.error,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
    },
    stopButtonText: {
      fontSize: 16,
      color: Colors.onError,
    },
    summaryCard: {
      backgroundColor: Colors.surface,
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
      shadowColor: Colors.inverseSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    summaryTitle: {
      fontSize: 20,
      color: Colors.onSurface,
      marginBottom: 8,
    },
    summaryHours: {
      fontSize: 32,
      color: Colors.primary,
      marginBottom: 16,
    },
    efficiencyContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    efficiencyLabel: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
    },
    efficiencyValue: {
      fontSize: 20,
      color: Colors.onSurface,
    },
    efficiencyBarContainer: {
      height: 8,
      backgroundColor: Colors.surfaceContainerHigh,
      borderRadius: 4,
      overflow: 'hidden',
    },
    efficiencyFill: {
      height: '100%',
      backgroundColor: Colors.primary,
      borderRadius: 4,
    },
  });

export const createMonthlyInsightsStyles = (Colors: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 24,
      paddingTop: 100,
    },
    // Top Bar
    topBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingBottom: 16,
      backgroundColor: Colors.background,
    },
    topBarLeft: {
      width: 40,
    },
    menuButton: {
      padding: 4,
      borderRadius: 999,
      backgroundColor: 'rgba(0,0,0,0.05)',
    },
    topBarCenter: {
      alignItems: 'center',
    },
    topBarTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: Colors.primary,
    },
    topBarDate: {
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: Colors.onSurfaceVariant,
      marginTop: 2,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: Colors.primaryContainer,
    },
    logoText: {
      fontSize: 24,
      fontWeight: '800',
      color: Colors.primary,
    },
    // Header
    headerSection: {
      marginBottom: 24,
    },
    headerSubtitle: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
      marginBottom: 4,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: Colors.primary,
      marginBottom: 16,
    },
    // Month Progress
    monthProgressSection: {
      marginBottom: 8,
    },
    monthProgressHeader: {
      flexDirection: 'row' as const,
      justifyContent: 'space-between' as const,
      alignItems: 'center' as const,
      marginBottom: 4,
    },
    monthProgressLabel: {
      fontSize: 12,
      fontWeight: '600' as const,
      color: `${Colors.primary}80`,
      letterSpacing: 0.5,
      textTransform: 'uppercase' as const,
    },
    monthProgressPercent: {
      fontSize: 12,
      fontWeight: '700' as const,
      color: Colors.primary,
    },
    monthProgressSub: {
      fontSize: 13,
      color: Colors.onSurfaceVariant,
      marginBottom: 10,
    },
    monthProgressBarContainer: {
      height: 8,
      backgroundColor: Colors.surfaceContainerHigh,
      borderRadius: 999,
      overflow: 'hidden' as const,
    },
    monthProgressBarFill: {
      height: '100%' as const,
      backgroundColor: Colors.primary,
      borderRadius: 999,
    },
    // Metrics Grid
    metricsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginBottom: 32,
      gap: 16,
    },
    metricCard: {
      width: (screenWidth - 48 - 16) / 2,
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 24,
      padding: 16,
      justifyContent: 'space-between',
      height: 160,
      shadowColor: '#7f5af0',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      elevation: 4,
    },
    gradientCard: {
      backgroundColor: 'transparent',
    },
    metricHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    trendBadge: {
      backgroundColor: `${Colors.tertiary}30`,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
    },
    trendPositive: {
      backgroundColor: `${Colors.tertiaryFixed}30`,
    },
    trendText: {
      fontSize: 10,
      fontWeight: '600',
      color: Colors.tertiary,
    },
    metricFooter: {
      marginTop: 'auto',
    },
    metricLabel: {
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: 4,
    },
    metricValue: {
      fontSize: 24,
      fontWeight: '800',
    },
    // Chart
    chartRow: {
      marginBottom: 32,
      gap: 16,
    },
    chartColumn: {
      marginBottom: 16,
    },
    chartContainer: {
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 32,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 12,
      elevation: 4,
    },
    chartHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
      marginBottom: 24,
    },
    chartTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: Colors.onSurface,
      marginBottom: 4,
    },
    chartSubtitle: {
      fontSize: 12,
      color: Colors.onSurfaceVariant,
    },
    legend: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    legendDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    legendText: {
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'uppercase',
      color: Colors.onSurfaceVariant,
    },
    barsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
      height: 200,
      gap: 12,
    },
    barItem: {
      flex: 1,
      alignItems: 'center',
    },
    barWrapper: {
      width: '100%',
      height: 160,
      justifyContent: 'flex-end',
    },
    barBackground: {
      width: '100%',
      height: '100%',
      backgroundColor: Colors.surfaceContainerLow,
      borderRadius: 12,
      overflow: 'hidden',
      justifyContent: 'flex-end',
    },
    barFill: {
      width: '100%',
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
    },
    barLabel: {
      marginTop: 12,
      fontSize: 12,
      fontWeight: 'bold',
      color: Colors.onSurfaceVariant,
    },
    // Peak Card
    peakColumn: {
      marginBottom: 16,
    },
    peakCard: {
      backgroundColor: Colors.surfaceContainerHigh,
      borderRadius: 32,
      padding: 24,
      position: 'relative',
      overflow: 'hidden',
      height: 200,
      justifyContent: 'center',
    },
    peakBlur: {
      position: 'absolute',
      right: -16,
      top: -16,
      width: 128,
      height: 128,
      borderRadius: 64,
      backgroundColor: `${Colors.tertiaryFixed}20`,
    },
    peakContent: {
      zIndex: 2,
    },
    peakIcon: {
      marginBottom: 12,
    },
    peakLabel: {
      fontSize: 12,
      fontWeight: 'bold',
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: Colors.onSurfaceVariant,
    },
    peakDay: {
      fontSize: 32,
      fontWeight: '800',
      color: Colors.primary,
      marginTop: 8,
      marginBottom: 6,
    },
    peakDescription: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
      lineHeight: 20,
      marginBottom: 16,
    },
    sessionCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: Colors.surface,
      borderLeftWidth: 4,
      borderRadius: 16,
      padding: 14,
      marginBottom: 12,
      shadowColor: Colors.inverseSurface,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    sessionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    sessionIconBg: {
      width: 44,
      height: 44,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sessionTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: Colors.onSurface,
    },
    sessionMeta: {
      fontSize: 12,
      color: Colors.onSurfaceVariant,
    },
    sessionRight: {
      alignItems: 'flex-end',
      justifyContent: 'center',
    },
    sessionDuration: {
      fontSize: 14,
      fontWeight: '800',
      color: Colors.primary,
    },
    sessionCategory: {
      fontSize: 12,
      color: Colors.onSurfaceVariant,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginTop: 2,
    },
    // ... additional styles not needed for now
    placeholderScreen: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
    },
    placeholderTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: Colors.primary,
      marginBottom: 8,
    },
    placeholderSub: {
      fontSize: 16,
      color: Colors.onSurfaceVariant,
      textAlign: 'center',
    },
  });

// ---------------------------------------------------------------------
// Week Analysis Styles
// ---------------------------------------------------------------------
export const createWeekAnalysisStyles = (Colors: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: Colors.background,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 24,
      paddingTop: 100,
    },
    heroSection: {
      marginBottom: 24,
    },
    heroSubtitle: {
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 1.5,
      color: Colors.primary,
      marginBottom: 4,
    },
    heroTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: Colors.onBackground,
    },
    emptyState: {
      marginTop: 48,
      borderRadius: 24,
      backgroundColor: Colors.surfaceContainerLow,
      padding: 32,
      alignItems: 'center',
      gap: 16,
    },
    emptyText: {
      color: Colors.onSurfaceVariant,
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 20,
    },

    // ---- Section label (shared) ----
    sectionLabel: {
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.5,
      color: Colors.primary,
      marginBottom: 16,
    },

    // ---- Week Comparison ----
    comparisonCard: {
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 24,
      padding: 24,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 4,
    },
    comparisonRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    comparisonMetric: {
      flex: 1,
      alignItems: 'center',
      gap: 6,
    },
    deltaChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
    },
    deltaUp: {
      backgroundColor: `${Colors.tertiary}12`,
    },
    deltaDown: {
      backgroundColor: `${Colors.error}12`,
    },
    deltaText: {
      fontSize: 13,
      fontWeight: '700',
    },
    comparisonBigNum: {
      fontSize: 22,
      fontWeight: '800',
      color: Colors.onBackground,
    },
    comparisonMetricLabel: {
      fontSize: 11,
      color: Colors.onSurfaceVariant,
      textAlign: 'center',
    },
    comparisonFooter: {
      fontSize: 12,
      color: Colors.outlineVariant,
      textAlign: 'center',
      marginTop: 14,
    },

    // ---- Daily Distribution ----
    distributionCard: {
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 24,
      padding: 24,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 4,
    },
    distRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
      gap: 12,
    },
    distDayLabel: {
      width: 36,
      fontSize: 13,
      fontWeight: '700',
      color: Colors.onSurfaceVariant,
    },
    distBarTrack: {
      flex: 1,
      height: 10,
      backgroundColor: Colors.surfaceContainerHigh,
      borderRadius: 5,
      overflow: 'hidden',
    },
    distBarFill: {
      height: '100%',
      borderRadius: 5,
      backgroundColor: Colors.primary,
    },
    distHours: {
      width: 56,
      fontSize: 13,
      fontWeight: '800',
      color: Colors.onBackground,
      textAlign: 'right',
    },

    // ---- Consistency Score ----
    consistencyCard: {
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 24,
      padding: 24,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 4,
    },
    consistencyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 24,
    },
    scoreRing: {
      width: 96,
      height: 96,
      justifyContent: 'center',
      alignItems: 'center',
    },
    scoreRingBg: {
      position: 'absolute',
      width: 88,
      height: 88,
      borderRadius: 44,
      borderWidth: 6,
      borderColor: Colors.surfaceContainerHigh,
    },
    scoreRingFg: {
      position: 'absolute',
      width: 88,
      height: 88,
      borderRadius: 44,
      borderWidth: 6,
      borderColor: Colors.primary,
      transform: [{ rotate: '-90deg' }],
    },
    scoreCenter: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    scoreNum: {
      fontSize: 28,
      fontWeight: '800',
    },
    consistencyInfo: {
      flex: 1,
      gap: 8,
    },
    consistencyTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: Colors.onBackground,
    },
    consistencyBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
    },
    consistencyBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    streakRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    streakText: {
      fontSize: 13,
      color: Colors.onSurfaceVariant,
    },

    // ---- Goal Pacing ----
    pacingCard: {
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 24,
      padding: 24,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 4,
    },
    pacingBarContainer: {
      marginBottom: 12,
    },
    pacingBarTrack: {
      height: 12,
      backgroundColor: Colors.surfaceContainerHigh,
      borderRadius: 6,
      overflow: 'hidden',
      position: 'relative',
    },
    pacingBarFill: {
      height: '100%',
      borderRadius: 6,
      backgroundColor: Colors.primary,
    },
    pacingGoalMarker: {
      position: 'absolute',
      top: -4,
      width: 2,
      height: 20,
    },
    pacingGoalLine: {
      width: 2,
      height: 20,
      borderRadius: 1,
    },
    pacingLabels: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 6,
      marginBottom: 16,
    },
    pacingActual: {
      fontSize: 24,
      fontWeight: '800',
      color: Colors.primary,
    },
    pacingGoal: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
    },
    pacingProjection: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 14,
      borderRadius: 16,
    },
    pacingProjectionText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
    },

    // ---- Notes Feed ----
    notesFeedCard: {
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 24,
      padding: 24,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 4,
    },
    notesEmpty: {
      alignItems: 'center',
      gap: 12,
      paddingVertical: 16,
    },
    notesEmptyText: {
      fontSize: 13,
      color: Colors.onSurfaceVariant,
      textAlign: 'center',
      lineHeight: 18,
    },
    noteItem: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    noteIconCol: {
      alignItems: 'center',
      width: 20,
      marginRight: 12,
    },
    noteDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: Colors.primary,
      marginTop: 4,
    },
    noteLine: {
      flex: 1,
      width: 2,
      backgroundColor: Colors.surfaceContainerHigh,
      marginTop: 4,
    },
    noteContent: {
      flex: 1,
      backgroundColor: Colors.surfaceContainerLow,
      borderRadius: 16,
      padding: 14,
    },
    noteHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
    },
    noteDay: {
      fontSize: 13,
      fontWeight: '700',
      color: Colors.onBackground,
    },
    noteHours: {
      fontSize: 12,
      fontWeight: '700',
      color: Colors.primary,
    },
    noteText: {
      fontSize: 13,
      color: Colors.onSurfaceVariant,
      lineHeight: 18,
    },

    // ---- Week Selector Button ----
    weekSelectorButton: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      marginHorizontal: 24,
      marginBottom: 12,
      paddingHorizontal: 20,
      paddingVertical: 14,
      backgroundColor: Colors.surfaceContainerLowest,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: `${Colors.primary}30`,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 4,
    },
    weekSelectorButtonLeft: {
      flexDirection: 'column' as const,
      gap: 2,
    },
    weekSelectorButtonLabel: {
      fontSize: 10,
      fontWeight: '600' as const,
      textTransform: 'uppercase' as const,
      letterSpacing: 1,
      color: Colors.primary,
    },
    weekSelectorButtonRange: {
      fontSize: 15,
      fontWeight: '800' as const,
      color: Colors.onSurface,
    },

    // ---- Week Picker Modal ----
    weekPickerOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end' as const,
    },
    weekPickerSheet: {
      backgroundColor: Colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingTop: 12,
      paddingBottom: 32,
      maxHeight: '70%' as const,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 16,
    },
    weekPickerHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: Colors.outlineVariant,
      alignSelf: 'center' as const,
      marginBottom: 16,
    },
    weekPickerTitle: {
      fontSize: 18,
      fontWeight: '800' as const,
      color: Colors.onSurface,
      paddingHorizontal: 24,
      marginBottom: 16,
    },
    weekPickerItem: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderBottomWidth: 1,
      borderBottomColor: Colors.surfaceContainerHigh,
    },
    weekPickerItemSelected: {
      backgroundColor: `${Colors.primary}10`,
    },
    weekPickerItemLeft: {
      flexDirection: 'column' as const,
      gap: 3,
    },
    weekPickerItemRange: {
      fontSize: 15,
      fontWeight: '700' as const,
      color: Colors.onSurface,
    },
    weekPickerItemRangeSelected: {
      color: Colors.primary,
    },
    weekPickerItemBadge: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
      backgroundColor: `${Colors.tertiary}20`,
      alignSelf: 'flex-start' as const,
    },
    weekPickerItemBadgeText: {
      fontSize: 10,
      fontWeight: '700' as const,
      color: Colors.tertiary,
      textTransform: 'uppercase' as const,
      letterSpacing: 0.5,
    },
    weekPickerEmpty: {
      paddingVertical: 32,
      alignItems: 'center' as const,
    },
    weekPickerEmptyText: {
      fontSize: 14,
      color: Colors.onSurfaceVariant,
    },
  });

// This is a utility file, not a route screen
export default null;
