export const tabLightTheme = {
  primary: '#7f5af0',
  onPrimary: '#ffffff',
  primaryContainer: '#c77bff',
  onPrimaryContainer: '#f0e6ff',
  primaryFixed: '#dcb8ff',
  primaryFixedDim: '#b48bff',
  secondary: '#9f63ff',
  onSecondary: '#ffffff',
  secondaryContainer: '#959efd',
  onSecondaryContainer: '#27308a',
  secondaryFixed: '#e0e0ff',
  secondaryFixedDim: '#bdc2ff',
  tertiary: '#6f2ce8',
  onTertiary: '#ffffff',
  tertiaryContainer: '#a673ff',
  onTertiaryContainer: '#f1dcff',
  tertiaryFixed: '#c09dff',
  tertiaryFixedDim: '#a06aff',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  background: '#f7f9fc',
  onBackground: '#191c1e',
  surface: '#f7f9fc',
  onSurface: '#191c1e',
  surfaceVariant: '#e0e3e6',
  onSurfaceVariant: '#424654',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f2f4f7',
  surfaceContainer: '#eceef1',
  surfaceContainerHigh: '#e6e8eb',
  surfaceContainerHighest: '#e0e3e6',
  inverseSurface: '#2d3133',
  inverseOnSurface: '#eff1f4',
  inversePrimary: '#c19dff',
  outline: '#737785',
  outlineVariant: '#c3c6d6',
  surfaceTint: '#7f5af0',
};

export const tabDarkTheme = {
  primary: '#c19dff',
  onPrimary: '#1a1a2a',
  primaryContainer: '#513aa7',
  onPrimaryContainer: '#e6dbff',
  primaryFixed: '#9c7ddf',
  primaryFixedDim: '#7a60b4',
  secondary: '#9b70ff',
  onSecondary: '#f2f0ff',
  secondaryContainer: '#4f3eba',
  onSecondaryContainer: '#e7e0ff',
  secondaryFixed: '#a89dff',
  secondaryFixedDim: '#7f73d1',
  tertiary: '#a276ff',
  onTertiary: '#ffffff',
  tertiaryContainer: '#5b4e9a',
  onTertiaryContainer: '#e9dcff',
  tertiaryFixed: '#bea5ff',
  tertiaryFixedDim: '#8f7dc5',
  error: '#ffb4b4',
  onError: '#3f0000',
  errorContainer: '#5d0106',
  onErrorContainer: '#ffd7d7',
  background: '#101424',
  onBackground: '#f2f4ff',
  surface: '#141a2b',
  onSurface: '#e8edff',
  surfaceVariant: '#1f2640',
  onSurfaceVariant: '#b6c1db',
  surfaceContainerLowest: '#0e1121',
  surfaceContainerLow: '#131a2d',
  surfaceContainer: '#1b2442',
  surfaceContainerHigh: '#232f56',
  surfaceContainerHighest: '#2d3d6a',
  inverseSurface: '#eceff9',
  inverseOnSurface: '#111827',
  inversePrimary: '#cfa0ff',
  outline: '#a0a8bf',
  outlineVariant: '#6a75a2',
  surfaceTint: '#c19dff',
};

// This is a utility file, not a route screen
export default null;

